#/bin/bash

time=10000
popGenome=500

### Script to generate a list of parameters with repetitions, each tagged with a unique seed
### The seed acts as an identifier to distinguish individual simulations
### Results are saved in the file "initialization_of_simulations.csv"
# ./creation_of_datasets.sh

# Input file is formated to be used as input parameters in the software
cat initialization_of_simulations.csv | tr -d "[:blank:]" | sed '1d' > params_format.csv

while IFS=, read -r id seed phi alpha bh dh bt dt pa popET
do
    # Select the output directory for the large data files generated by TEDyS using seed as unqieu identifier
    nameFile="./output/data_$seed.csv"

    echo "Launching ID $seed"
    echo "Initial population size: $popGenome"
    echo "bh        = $bh"
    echo "dh        = $dh"
    echo "alphah    = $alpha"
    echo "phi       = $phi"
    echo "bt        = $bt"
    echo "dt        = $dt"
    echo "pa        = $pa"
    echo "init_TE   = $popET"
    echo "duration  = $time"
    echo "file name = $nameFile"
    echo -e "\n"

    time python ./src/main.py -init $id -s $seed -bh $bh -dh $dh -a $alpha -phi $phi -bt $bt -dt $dt -pa $pa -popGenome $popGenome -popTe $popET -time $time -o $nameFile

done < params_format.csv

# rm params_format.csv
